// Generated by https://quicktype.io

export interface ChatResponse {
  _id: string;
  miembros: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Conversacion {
  _id: string;
  miembros: string[];
  createdAt: string;
  updatedAt: string;
  para: string;
  remitente: string;
}

// Generated by https://quicktype.io

export interface MensajesResp {
  ok: boolean;
  msg: string;
  mensajeGuardado: MensajeGuardado;
}

export interface MensajeGuardado {
  conversacion: string;
  remitente: string;
  mensaje: string;
  _id: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Conversacion {
  ok: boolean;
  mensajes: MensajeGuardado[];
}

// Generated by https://quicktype.io

export interface CrearChatResponse {
  ok: boolean;
  msg: string;
  guardarChat: GuardarChat;
}

export interface GuardarChat {
  miembros: string[];
  remitente: string;
  para: string;
  _id: string;
  createdAt: string;
  updatedAt: string;
}
