// Generated by https://quicktype.io

export interface ChatResponse {
  _id: string;
  miembros: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Conversacion {
  _id: string;
  miembros: string[];
  createdAt: string;
  updatedAt: string;
}
