// Generated by https://quicktype.io

export interface CrearInmuebleResp {
  ok: boolean;
  msg: string;
  inmueble: Inmueble;
  errors: Errors[];
}

interface Errors {
  msg: string;
  param: string;
  location: string;
}

export interface Inmueble {
  _id: string | null;
}

// Generated by https://quicktype.io

export interface BorrarInmuebleResp {
  ok: boolean;
  msg: string;
  inmuebleBorrado: InmuebleBorrado;
}

export interface InmuebleBorrado {
  _id: string;
  titulo: string;
  precio: number;
  publicado: boolean;
  usuario: string;
  categoria: string;
}
