// Generated by https://quicktype.io

export interface CrearInmuebleResp {
  ok: boolean;
  msg: string;
  inmueble: Inmueble;
}

export interface Inmueble {
  titulo: string | null;
  descripcion?: string | null;
  precio?: number | null;
  publicado?: boolean | null;
  usuario?: string | null;
  categoria?: string | null;
  AA?: number | null;
  IID?: string | null;
  agua?: boolean | null;
  amueblado?: boolean | null;
  antiguedad?: string | null;
  baños?: number | null;
  camas?: number | null;
  closet?: number | null;
  cocina?: number | null;
  comedor?: number | null;
  comisiones?: number | null;
  discapacitados?: boolean | null;
  escuelas?: boolean | null;
  estufa?: boolean | null;
  gas?: boolean | null;
  habitaciones?: number | null;
  horno?: boolean | null;
  internet?: boolean | null;
  lavadora?: boolean | null;
  luz?: boolean | null;
  m2Construidos?: number | null;
  m2Terreno?: number | null;
  mantenimiento?: boolean | null;
  medioBaños?: number | null;
  microondas?: boolean | null;
  minihorno?: boolean | null;
  otros?: string | null;
  parking?: number | null;
  piscinas?: boolean | null;
  pisos?: number | null;
  propertyType?: string | null;
  refrigerador?: number | null;
  sala?: number | null;
  secadora?: boolean | null;
  seguridadPrivada?: boolean | null;
  _id?: string | null;
}
