// Generated by https://quicktype.io

export interface FavResp {
  ok: boolean;
  msg: string;
  favorito: Favorito;
  errors: Errors[];
}

export interface Favorito {
  _id: string;
  inmueble: Inmueble;
  createdAt: string;
  updatedAt: string;
  solicitud: Solicitud;
  propietario: string;
}

interface Errors {
  msg: string;
  param: string;
  location: string;
}

interface Inmueble {
  _id: string;
  titulo: string;
  usuario: Usuario;
  slug: string;
  imgs: string[];
}

interface Usuario {
  _id: string;
  nombre: string;
  apellido: string;
}

export interface FavData {
  usuario: string | null | undefined;
  inmueble: string;
  propietario: string;
}

export type Solicitud = "Pendiente" | "Aprobado" | "Rechazado";
