// Generated by https://quicktype.io

export interface FavResp {
  ok: boolean;
  msg: string;
  favorito: Favorito;
  errors: Errors[];
}

export interface Favorito {
  _id: string;
  usuario: string;
  inmueble: string;
  createdAt: string;
  updatedAt: string;
}

interface Errors {
  msg: string;
  param: string;
  location: string;
}

export interface FavData {
  usuario: string | null | undefined;
  inmueble: string;
}
