export interface HistorialResp {
  ok: boolean;
  msg: string;
  total: number;
  historialUsuario: HistorialUsuario[];
}

export interface HistorialUsuario {
  _id: string;
  usuario: string;
  inmueble: Inmueble;
  createdAt: string;
  updatedAt: string;
}

export interface Inmueble {
  _id: string;
  titulo: string;
  slug: string;
}

export interface HistData {
  usuario: string | null | undefined;
  inmueble: string;
}

// Generated by https://quicktype.io

export interface HistorialPagosResp {
  ok: boolean;
  msg: string;
  pedidosUsuario: PedidosUsuario[];
}

export interface PedidosUsuario {
  _id: string;
  usuario: string;
  paquete: string;
  precio: number;
  importe: number;
  fechaPago: string;
  fechaVencimiento: string;
  metodoPago: string;
  vigencia: boolean;
  idStripe: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
