// Generated by https://quicktype.io

export interface InmueblesResponse {
  ok: boolean;
  total: number;
  inmuebles: Inmueble[];
}

export interface Inmueble {
  _id: string;
  titulo: string;
  descripcion: string;
  precio: number;
  publicado: boolean;
  usuario: Usuario;
  categoria: Categoria;
  AA?: number;
  IID?: string;
  agua?: boolean;
  amueblado?: boolean;
  antiguedad?: string;
  baños?: number;
  camas?: number;
  closet?: number;
  cocina?: number;
  comedor?: number;
  comisiones?: number;
  discapacitados?: boolean;
  escuelas?: boolean;
  estufa?: boolean;
  gas?: boolean;
  habitaciones?: number;
  horno?: boolean;
  internet?: boolean;
  lavadora?: boolean;
  luz?: boolean;
  m2Construidos?: number;
  m2Terreno?: number;
  mantenimiento?: boolean;
  medioBaños?: number;
  microondas?: boolean;
  minihorno?: boolean;
  otros?: string;
  parking?: number;
  piscinas?: boolean;
  pisos?: number;
  propertyType?: string;
  refrigerador?: number;
}

export interface Categoria {
  _id: string;
  nombre: string;
}

export interface Usuario {
  _id: string;
  nombre: string;
  apellido: string;
  correo: string;
}

export interface CategoriesResponse {
  ok: boolean;
  total: number;
  categorias: Categoria[];
}
