// Generated by https://quicktype.io

export interface MensajesRespuesta {
  ok: boolean;
  mensajes: Mensaje[];
}

export interface Mensaje {
  _id: string;
  conversacion: string;
  remitente: string;
  mensaje: string;
  para: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
