// Generated by https://quicktype.io

export interface MISUsuariosResp {
  ok: boolean;
  total: number;
  usuariosPagados: UsuariosPagado[];
}

export interface UsuariosPagado {
  usuario: string;
  nombre: string;
  expireAt: string;
  createdAt: string;
  uid: string;
}
