// Generated by https://quicktype.io

export interface PaqueteIndividualResp {
  ok: boolean;
  msg: string;
  paquete: PaqueteIndividual;
}

export interface PaqueteIndividual {
  _id: string;
  nombre: string;
  descripcion: string;
  precioAnual: number;
  precioSemestral: number;
  precioTrimestral: number;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
