// Generated by https://quicktype.io

export interface PedidoIndividualResp {
  ok: boolean;
  msg: string;
  pedido: Pedido;
}

export interface Pedido {
  usuario: string | undefined | null;
  paquete: string | undefined;
  precio: number;
  importe: number;
  fechaPago: string;
  fechaVencimiento: string;
  metodoPago: string | undefined;
  vigencia: boolean;
  idPago: string | undefined;
  totalUsuarios?: number;
  _id?: string;
  createdAt?: string;
  updatedAt?: string;
}
