// Generated by https://quicktype.io

export interface TipoPropiedadResp {
  ok: boolean;
  total: number;
  tipoPropiedad: TipoPropiedad[];
}

export interface TipoPropiedad {
  _id: string;
  nombre: string;
  createdAt: string;
  updatedAt: string;
}
