// Generated by https://quicktype.io

export interface ReferenciasUsuarioResp {
  ok: boolean;
  msg: string;
  referencias: Referencia[];
}

export interface Referencia {
  _id: string;
  usuario: string;
  paquete: Paquete;
  referencia: string;
  precio: number;
  importe: number;
  totalUsuarios: number;
  createdAt: string;
  updatedAt: string;
}

interface Paquete {
  _id: string;
  nombre: string;
}
