// Generated by https://quicktype.io

export interface ReferenciasUsuarioResp {
  ok: boolean;
  msg: string;
  referencias: Referencia[];
  total: number;
}

export interface ReferenciaNumero {
  ok: boolean;
  msg: string;
  referencia: Referencia;
}

export interface NuevaReferencia {
  ok: boolean;
  msg: string;
  nuevaRef: Referencia;
}

export interface Referencia {
  _id: string;
  usuario: Usuario;
  paquete: Paquete;
  referencia: string;
  precio: number;
  importe: number;
  totalUsuarios: number;
  createdAt: string;
  updatedAt: string;
  estado: boolean;
  comprobante: string;
}

interface Paquete {
  _id: string;
  nombre: string;
}

interface Usuario {
  _id: string;
  nombre: string;
  apellido: string;
  correo: string;
  img: string;
  role: string;
  telefonoOficina: string;
  telefonoPersonal: string;
}
