// Generated by https://quicktype.io

export interface SolicitudResp {
  ok: boolean;
  msg: string;
  solicitud: Solicitud;
}

export interface Solicitud {
  usuario: Usuario;
  propietario: string;
  inmueble: Inmueble;
  estado: Estado;
  _id: string;
  nombre?: string;
  apellido?: string;
  titulo?: string;
  slug?: string;
}

// Generated by https://quicktype.io

export interface ObtenerSolicitud {
  ok: boolean;
  solicitudes: Solicitud[];
  msg: string;
  total: number;
}

export interface Inmueble {
  _id: string;
  titulo: string;
  slug: string;
}

export interface Usuario {
  _id: string;
  nombre: string;
  apellido: string;
}

type Estado = "Aprobado" | "Rechazado" | "Pendiente";
