// Generated by https://quicktype.io

export interface SolicitudResp {
  ok: boolean;
  msg: string;
  solicitud: Solicitud;
}

export interface Solicitud {
  usuario: string;
  propietario: string;
  inmueble: string;
  estado: boolean;
  _id: string;
}
